"""
Branch aliases used by build_dataset.py.

Keys are normalized branch names from meta.json. Values are canonical field
groups used for broad student-facing searches without dropping exact branch
names from the dataset.
"""

CANONICAL_BRANCH_LABELS = {
    "CSE_GROUP": "Computer Science (all variants)",
    "IT_GROUP": "Information Technology",
    "AI_DS_GROUP": "AI, Data Science and Machine Learning",
    "CYBER_IOT_GROUP": "Cyber Security, IoT and Blockchain",
    "ELECTRICAL_GROUP": "Electrical Engineering",
    "ELECTRONICS_GROUP": "Electronics and Communication",
    "MECHANICAL_GROUP": "Mechanical, Automation and Robotics",
    "CIVIL_GROUP": "Civil and Infrastructure",
    "CHEMICAL_GROUP": "Chemical and Petrochemical",
    "TEXTILE_GROUP": "Textile Technology",
    "PLASTIC_POLYMER_GROUP": "Plastic and Polymer",
    "OIL_PAINT_GROUP": "Oil, Paint and Surface Coating",
    "FOOD_GROUP": "Food Technology",
    "BIOTECH_GROUP": "Biotechnology and Biomedical",
    "ARCHITECTURE_GROUP": "Architecture and Planning",
    "AGRICULTURE_GROUP": "Agricultural Engineering",
    "AERONAUTICAL_GROUP": "Aeronautical Engineering",
    "AUTOMOBILE_GROUP": "Automobile Engineering",
    "INSTRUMENTATION_GROUP": "Instrumentation and Control",
    "MANUFACTURING_PRODUCTION_GROUP": "Manufacturing and Production",
    "METALLURGY_GROUP": "Metallurgy and Materials",
    "MINING_GROUP": "Mining Engineering",
    "PHARMACEUTICAL_GROUP": "Pharmaceutical and Fine Chemical",
    "PRINTING_PACKAGING_GROUP": "Printing and Packaging",
    "SAFETY_FIRE_GROUP": "Safety and Fire Engineering",
}

BRANCH_ALIASES = {
    "5g": "CYBER_IOT_GROUP",
    "aeronautical engineering": "AERONAUTICAL_GROUP",
    "agricultural engineering": "AGRICULTURE_GROUP",
    "architectural assistantship": "ARCHITECTURE_GROUP",
    "artificial intelligence": "AI_DS_GROUP",
    "artificial intelligence (ai) and data science": "AI_DS_GROUP",
    "artificial intelligence and data science": "AI_DS_GROUP",
    "artificial intelligence and machine learning": "AI_DS_GROUP",
    "automation and robotics": "MECHANICAL_GROUP",
    "automobile engineering": "AUTOMOBILE_GROUP",
    "automotive technology": "AUTOMOBILE_GROUP",
    "bio medical engineering": "BIOTECH_GROUP",
    "bio technology": "BIOTECH_GROUP",
    "chemical engineering": "CHEMICAL_GROUP",
    "civil engineering": "CIVIL_GROUP",
    "civil engineering and planning": "CIVIL_GROUP",
    "civil engineering[direct second year second shift]": "CIVIL_GROUP",
    "civil and environmental engineering": "CIVIL_GROUP",
    "civil and infrastructure engineering": "CIVIL_GROUP",
    "computer engineering": "CSE_GROUP",
    "computer engineering (regional language)": "CSE_GROUP",
    "computer engineering (software engineering)": "CSE_GROUP",
    "computer engineering[direct second year second shift]": "CSE_GROUP",
    "computer science": "CSE_GROUP",
    "computer science and business systems": "CSE_GROUP",
    "computer science and design": "CSE_GROUP",
    "computer science and engineering": "CSE_GROUP",
    "computer science and engineering (artificial intelligence and data science)": "AI_DS_GROUP",
    "computer science and engineering (artificial intelligence)": "AI_DS_GROUP",
    "computer science and engineering (cyber security)": "CYBER_IOT_GROUP",
    "computer science and engineering (internet of things and cyber security including block chain technology)": "CYBER_IOT_GROUP",
    "computer science and engineering (iot)": "CYBER_IOT_GROUP",
    "computer science and engineering(artificial intelligence and machine learning)": "AI_DS_GROUP",
    "computer science and engineering(cyber security)": "CYBER_IOT_GROUP",
    "computer science and engineering(data science)": "AI_DS_GROUP",
    "computer science and information technology": "CSE_GROUP",
    "computer science and technology": "CSE_GROUP",
    "computer technology": "CSE_GROUP",
    "cyber security": "CYBER_IOT_GROUP",
    "data engineering": "AI_DS_GROUP",
    "data science": "AI_DS_GROUP",
    "electrical engg[electronics and power]": "ELECTRICAL_GROUP",
    "electrical engineering": "ELECTRICAL_GROUP",
    "electrical and computer engineering": "ELECTRICAL_GROUP",
    "electrical and electronics engineering": "ELECTRICAL_GROUP",
    "electrical, electronics and power": "ELECTRICAL_GROUP",
    "electronics engineering": "ELECTRONICS_GROUP",
    "electronics engineering ( vlsi design and technology)": "ELECTRONICS_GROUP",
    "electronics and biomedical engineering": "ELECTRONICS_GROUP",
    "electronics and communication (advanced communication technology)": "ELECTRONICS_GROUP",
    "electronics and communication engineering": "ELECTRONICS_GROUP",
    "electronics and communication(advanced communication technology)": "ELECTRONICS_GROUP",
    "electronics and computer engineering": "ELECTRONICS_GROUP",
    "electronics and computer science": "ELECTRONICS_GROUP",
    "electronics and telecommunication engg": "ELECTRONICS_GROUP",
    "electronics and telecommunication engg[direct second year second shift]": "ELECTRONICS_GROUP",
    "fashion technology": "TEXTILE_GROUP",
    "food technology": "FOOD_GROUP",
    "food technology and management": "FOOD_GROUP",
    "industrial iot": "CYBER_IOT_GROUP",
    "information technology": "IT_GROUP",
    "instrumentation engineering": "INSTRUMENTATION_GROUP",
    "instrumentation and control engineering": "INSTRUMENTATION_GROUP",
    "internet of things (iot)": "CYBER_IOT_GROUP",
    "man made textile technology": "TEXTILE_GROUP",
    "manufacturing science and engineering": "MANUFACTURING_PRODUCTION_GROUP",
    "mechanical & automation engineering": "MECHANICAL_GROUP",
    "mechanical engineering": "MECHANICAL_GROUP",
    "mechanical engineering automobile": "AUTOMOBILE_GROUP",
    "mechanical engineering[sandwich]": "MECHANICAL_GROUP",
    "mechanical and mechatronics engineering (additive manufacturing)": "MECHANICAL_GROUP",
    "mechatronics engineering": "MECHANICAL_GROUP",
    "metallurgy and material technology": "METALLURGY_GROUP",
    "mining engineering": "MINING_GROUP",
    "oil fats and waxes technology": "OIL_PAINT_GROUP",
    "oil technology": "OIL_PAINT_GROUP",
    "oil and paints technology": "OIL_PAINT_GROUP",
    "paints technology": "OIL_PAINT_GROUP",
    "paper and pulp technology": "CHEMICAL_GROUP",
    "petro chemical engineering": "CHEMICAL_GROUP",
    "petro chemical technology": "CHEMICAL_GROUP",
    "pharmaceutical and fine chemical technology": "PHARMACEUTICAL_GROUP",
    "plastic technology": "PLASTIC_POLYMER_GROUP",
    "plastic and polymer engineering": "PLASTIC_POLYMER_GROUP",
    "plastic and polymer technology": "PLASTIC_POLYMER_GROUP",
    "printing technology": "PRINTING_PACKAGING_GROUP",
    "printing and packing technology": "PRINTING_PACKAGING_GROUP",
    "production engineering": "MANUFACTURING_PRODUCTION_GROUP",
    "production engineering[sandwich]": "MANUFACTURING_PRODUCTION_GROUP",
    "robotics": "MECHANICAL_GROUP",
    "robotics and artificial intelligence": "AI_DS_GROUP",
    "robotics and automation": "MECHANICAL_GROUP",
    "safety and fire engineering": "SAFETY_FIRE_GROUP",
    "structural engineering": "CIVIL_GROUP",
    "surface coating technology": "OIL_PAINT_GROUP",
    "technical textiles": "TEXTILE_GROUP",
    "textile chemistry": "TEXTILE_GROUP",
    "textile engineering / technology": "TEXTILE_GROUP",
    "textile plant engineering": "TEXTILE_GROUP",
    "textile technology": "TEXTILE_GROUP",
}


def normalize_branch(value):
    return " ".join(str(value or "").replace("\u00c2", "").split()).lower()


def canonical_branch_for(branch):
    normalized = normalize_branch(branch)
    return BRANCH_ALIASES.get(normalized, normalized)
